//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1IngSw.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Asignaturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asignaturas()
        {
            this.Temas = new HashSet<Temas>();
        }
        [Display(Name = "Identificador Asignatura")]
        [Editable(false)]
        public int IDAsignatura { get; set; }
        [Display(Name = "Grado")]
        [Editable(false)]
        public Nullable<int> IDGrado { get; set; }
        [Display(Name = "Nombre de la Asignatura")]
        [Required(ErrorMessage = "* Campo obligatorio")]
        public string Descripcion { get; set; }

        public virtual Grado Grado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temas> Temas { get; set; }
    }
}
