//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1IngSw.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Asignaturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asignaturas()
        {
            this.Temas = new HashSet<Temas>();
        }
        [DisplayName("Asignatura")]
        public int IDAsignatura { get; set; }
        [DisplayName("Grado")]
        public Nullable<int> IDGrado { get; set; }
        [DisplayName("Nombre Asignatura")]
        public string Descripcion { get; set; }
    
        public virtual Grado Grado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temas> Temas { get; set; }
    }
}
