//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1IngSw.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Temas()
        {
            this.Test = new HashSet<Test>();
        }
    
        public int IDTema { get; set; }
        public Nullable<int> IDAsignatura { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Asignaturas Asignaturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Test { get; set; }
    }
}
