//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1IngSw.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TestPreguntas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestPreguntas()
        {
            this.TestRespuestas = new HashSet<TestRespuestas>();
        }
        [Display(Name = "Identificador Pregunta")]
        [Editable(false)]
        public int IDPregunta { get; set; }
        [Display(Name = "Tema")]
        public Nullable<int> IDTema { get; set; }
        [Display(Name = "Descripción Pregunta")]
        [Required(ErrorMessage = "* Campo obligatorio")]
        public string Descripcion { get; set; }
    
        public virtual Temas Temas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestRespuestas> TestRespuestas { get; set; }
    }
}
