//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1IngSw.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTemas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestTemas()
        {
            this.TestRespuestas = new HashSet<TestRespuestas>();
        }
    
        public int IDTest { get; set; }
        public Nullable<int> IDTema { get; set; }
        public string Descripcion { get; set; }
        public Nullable<short> Orden { get; set; }
    
        public virtual Temas Temas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestRespuestas> TestRespuestas { get; set; }
    }
}
