//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1IngSw.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestPlataformaEntities : DbContext
    {
        public TestPlataformaEntities()
            : base("name=TestPlataformaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asignaturas> Asignaturas { get; set; }
        public virtual DbSet<Grado> Grado { get; set; }
        public virtual DbSet<RolesUsuario> RolesUsuario { get; set; }
        public virtual DbSet<Temas> Temas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TestPreguntas> TestPreguntas { get; set; }
        public virtual DbSet<TestRespuestas> TestRespuestas { get; set; }
    }
}
