//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1IngSw.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IDUsuario { get; set; }
        public Nullable<int> IDRol { get; set; }
        public string Nombre { get; set; }
        public byte[] Password { get; set; }
    
        public virtual RolesUsuario RolesUsuario { get; set; }
    }
}
